# Generated by Django 4.2 on 2023-04-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rat', '0002_create_groups'),
        ('Book_Rat', '0005_remove_book_description'),
    ]

    operations = [
    ]
