# Generated by Django 4.2 on 2023-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rat', '0006_merge_0002_create_groups_0005_remove_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
