# Generated by Django 4.2 on 2023-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rat', '0007_book_cover_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
